# Generated by Django 4.2 on 2023-05-20 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_menu_options_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main_app.menu', verbose_name='Блюдо')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
