# Generated by Django 4.2 on 2023-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_pizzarestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzarestaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images'),
        ),
    ]
